server:
  port: 8090
  use_grpc: false
redis:
  addr: "127.0.0.1:6379"
  user: ""
  password: ""
logger:
  level: "INFO"
ip_list:
  # key in redis for command HSet
  blacklist_addr: "black"
  # key in redis for command HSet
  whitelist_addr: "white"
limiter:
  ip:
    count: 1000
    interval: 1m
  login:
    count: 10
    interval: 1m
  password:
    count: 100
    interval: 1m
